/**
 * Embed the engine's text font so every machine draws text identically.
 *
 * Usage: node scripts/embed-fonts.mjs <@fontsource-variable/roboto dir>
 *
 * Text nodes default to Roboto, but nothing ever loaded it: a machine with
 * Roboto installed drew it, one without fell back to Arial or Helvetica,
 * and every text width - and so every layout and every audit verdict -
 * depended on the machine. This writes the Latin, Latin Extended and Greek
 * subsets of the variable Roboto (every weight the text roles use, 450 to
 * 700) as base64 into `src/lib/theme/fonts/roboto.ts`, which the engine
 * registers before a beat renders and wire measures text with.
 */
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const source = process.argv[2];
if (!source) throw new Error('usage: embed-fonts.mjs <fontsource roboto dir>');
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '../src/lib/theme/fonts');
const SUBSETS = ['latin', 'latin-ext', 'greek'];

const css = fs.readFileSync(path.join(source, 'wght.css'), 'utf8');
const faces = [];
for (const subset of SUBSETS) {
  const file = `roboto-${subset}-wght-normal.woff2`;
  const block = css
    .split('@font-face')
    .find(b => b.includes(`/${file}`) || b.includes(`files/${file}`));
  const range = block?.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
  if (!range) throw new Error(`no unicode-range for ${subset}`);
  const data = fs.readFileSync(path.join(source, 'files', file));
  faces.push({subset, range, data: data.toString('base64')});
}

fs.mkdirSync(OUT, {recursive: true});
fs.copyFileSync(
  path.join(source, 'LICENSE'),
  path.join(OUT, 'LICENSE-roboto.txt'),
);
const body = faces
  .map(
    f =>
      `  {\n    subset: '${f.subset}',\n    unicodeRange: '${f.range}',\n    woff2: '${f.data}',\n  },`,
  )
  .join('\n');
fs.writeFileSync(
  path.join(OUT, 'roboto.ts'),
  `/* eslint-disable */
// Generated by scripts/embed-fonts.mjs from @fontsource-variable/roboto
// (SIL Open Font License 1.1, see LICENSE-roboto.txt). Do not edit.

export interface EmbeddedFontFace {
  readonly subset: string;
  readonly unicodeRange: string;
  /** The WOFF2 file, base64. */
  readonly woff2: string;
}

/** Variable Roboto (weights 100-900), the engine's text font. */
export const ROBOTO_FACES: readonly EmbeddedFontFace[] = [
${body}
];
`,
);
console.log(
  `wrote ${faces.length} faces, ${faces.reduce((s, f) => s + f.data.length, 0)} base64 chars`,
);
