import {
  compileBeatSource,
  type CompileDiagnostic,
} from '@ovacanvas/host/authoring';
import * as path from 'path';
import {fileURLToPath} from 'url';
import {generateBeatSource, type SourceMap} from '../codegen/generate.js';
import {hasErrors, type Issue} from '../document/issues.js';
import type {SceneDocument} from '../document/model.js';

/**
 * The directory generated modules are typechecked from. Any directory whose
 * `node_modules` resolves the installed `@ovacanvas/*` packages works; the
 * host package is the one the studio already compiles against.
 */
export const DEFAULT_COMPILE_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../host',
);

export interface CompiledDocument {
  readonly ok: boolean;
  /** The generated TypeScript module ('' when validation failed). */
  readonly source: string;
  /** CommonJS the browser resolves with `resolveBeatSource` ('' unless ok). */
  readonly code: string;
  readonly sourceMap: SourceMap;
  readonly issues: readonly Issue[];
  readonly durationSeconds: number;
  /** The core document that was compiled (the expansion, for kit documents). */
  readonly document?: SceneDocument;
  /** Expanded node id to kit instance id. */
  readonly origins: Readonly<Record<string, string>>;
}

/**
 * Validate, generate and typecheck a document in one call.
 *
 * @remarks
 * The TypeScript pass is a backstop, not the main line of defence: the
 * validator already rejects everything it can see statically. What the
 * compiler adds is the exact shape of `json` props (projections, geo
 * sources, 3D worlds) and protection against the generator itself drifting
 * from the engine. Its diagnostics are located on the node or step that
 * produced the failing line, through the generator's source map, so even a
 * backstop failure reads like a validator issue.
 */
export function compileDocument(
  input: unknown,
  options: {projectRoot?: string} = {},
): CompiledDocument {
  const generated = generateBeatSource(input);
  if (hasErrors(generated.issues)) {
    return {...generated, ok: false, code: ''};
  }
  const compiled = compileBeatSource(
    generated.source,
    options.projectRoot ?? DEFAULT_COMPILE_ROOT,
    '__wire_beat__.ts',
  );
  if (compiled.ok) {
    return {...generated, ok: true, code: compiled.code};
  }
  const located = compiled.diagnostics
    .map(diagnostic =>
      locateDiagnostic(diagnostic, generated.sourceMap, generated.source),
    )
    .map(issue => {
      const kit =
        issue.node !== undefined ? generated.origins[issue.node] : undefined;
      return kit
        ? {
            ...issue,
            node: kit,
            hint: `${issue.hint ?? ''} (generated by kit ${kit})`,
          }
        : issue;
    });
  return {
    ...generated,
    ok: false,
    code: '',
    issues: [...generated.issues, ...located],
  };
}

export function locateDiagnostic(
  diagnostic: CompileDiagnostic,
  sourceMap: SourceMap,
  source: string,
): Issue {
  const line = diagnostic.line;
  let node: string | undefined;
  let step: string | undefined;
  if (line !== null) {
    for (const [id, range] of Object.entries(sourceMap.nodes)) {
      if (line >= range.start && line <= range.end) node = id;
    }
    // Otherwise, the step that starts nearest at or before the line. Every
    // step (nested ones included) starts on its own line, so this is exact
    // for a step's first line and names the enclosing step for the rest.
    if (node === undefined) {
      let best = -1;
      for (const [pathKey, stepLine] of Object.entries(sourceMap.steps)) {
        if (stepLine <= line && stepLine > best) {
          best = stepLine;
          step = pathKey;
        }
      }
    }
  }
  const text = line !== null ? source.split('\n')[line - 1]?.trim() : undefined;
  return {
    code: 'typescript',
    severity: 'error',
    message: diagnostic.message,
    ...(node ? {node} : {}),
    ...(step ? {step} : {}),
    ...(text ? {hint: `generated line ${line}: ${text}`} : {}),
  };
}
